#!/usr/bin/env node

var Program = require("commander");
var ListDispenser = require("classes/ListDispenser.js");

function additionalHelp(){
	console.log("Additional help...");
}

Program
	.version("1.0.0")
	//.option("-o, --output_path <path>", "Output Path")
	//.option("-i, --input_path <path>", "Input Path")
	

Program
	.command("dispense [path]")
	.description("Retrieves records in batched amounts from a directory containing lists.")
	.option("-o, --output_path <path>", "Output Path")
	//.option("-i, --input_path <path>", "Input Path")
	.action(function(inputPath, options){
		ListDispenser.dispense(inputPath);
	});

Program
	.command("*")
	.description("Runs main")
	.action(function(){

	});

Program.on("--help", additionalHelp);

Program.parse(process.argv);